//! Handler registry: every Python handler module and its COMMANDS.
//!
//! Generated from `dippy.cli.KNOWN_HANDLERS`; modules not ported yet keep
//! `PORTED = false` and always ask.

use super::*;

macro_rules! handler {
    ($m:ident) => {
        Handler {
            module: stringify!($m),
            commands: $m::COMMANDS,
            classify: $m::classify,
            description: $m::DESCRIPTION,
            ported: $m::PORTED,
        }
    };
}

pub static HANDLERS: &[Handler] = &[
    handler!(sevenz),
    handler!(ansible),
    handler!(arch),
    handler!(auth0),
    handler!(awk),
    handler!(aws),
    handler!(azure),
    handler!(binhex),
    handler!(black),
    handler!(brew),
    handler!(caffeinate),
    handler!(cargo),
    handler!(cdk),
    handler!(codesign),
    handler!(compression_tool),
    handler!(copy_move),
    handler!(curl),
    handler!(defaults),
    handler!(dippy_cli),
    handler!(diskutil),
    handler!(dmesg),
    handler!(docker),
    handler!(dscl),
    handler!(duckdb),
    handler!(env),
    handler!(fd),
    handler!(find),
    handler!(fzf),
    handler!(gcloud),
    handler!(gh),
    handler!(git),
    handler!(gzip),
    handler!(hdiutil),
    handler!(helm),
    handler!(iconv),
    handler!(ifconfig),
    handler!(ip),
    handler!(isort),
    handler!(journalctl),
    handler!(kubectl),
    handler!(launchctl),
    handler!(lipo),
    handler!(mdimport),
    handler!(mktemp),
    handler!(mysql),
    handler!(networksetup),
    handler!(npm),
    handler!(open),
    handler!(openssl),
    handler!(packer),
    handler!(pip),
    handler!(pkgutil),
    handler!(plutil),
    handler!(pre_commit),
    handler!(profiles),
    handler!(prometheus),
    handler!(psql),
    handler!(pytest),
    handler!(python),
    handler!(qlmanage),
    handler!(rtk),
    handler!(ruff),
    handler!(sample),
    handler!(say),
    handler!(script),
    handler!(scutil),
    handler!(security),
    handler!(sed),
    handler!(shell),
    handler!(sips),
    handler!(sort),
    handler!(spctl),
    handler!(sqlcmd),
    handler!(sqlite3),
    handler!(ssh),
    handler!(sudo),
    handler!(symbols),
    handler!(sysctl),
    handler!(tar),
    handler!(tee),
    handler!(terraform),
    handler!(textutil),
    handler!(tmutil),
    handler!(uv),
    handler!(wget),
    handler!(xargs),
    handler!(xattr),
    handler!(xxd),
    handler!(yq),
];
