//! Replay SQL checker calls recorded by `rust/parity/sql_collect.py` or
//! generated by `rust/parity/sql_fuzz.py`.
//!
//! Reads JSON lines `{"fn": ..., "sql": ..., "opts": {...}}` on stdin and
//! writes one JSON line `{"rs": <result>}` per input, in order.

use std::io::{BufRead, Write};

use dippy_rs::sql::{
    ReadonlyOptions, duckdb_copy_export_target, duckdb_writes_only_main, is_readonly_sql,
    split_sql_statements,
};
use serde_json::{Value, json};

fn words(value: Option<&Value>) -> Vec<String> {
    value
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(|v| v.as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default()
}

fn flag(opts: &Value, key: &str, default: bool) -> bool {
    opts.get(key).and_then(Value::as_bool).unwrap_or(default)
}

fn run(item: &Value) -> Value {
    let sql = item["sql"].as_str().unwrap_or_default();
    let opts = &item["opts"];
    match item["fn"].as_str() {
        Some("is_readonly_sql") => {
            let options = ReadonlyOptions {
                extra_readonly: words(opts.get("extra_readonly")),
                extra_write: words(opts.get("extra_write")),
                allow_multiple: flag(opts, "allow_multiple", false),
                allow_temp_tables: flag(opts, "allow_temp_tables", false),
                bracket_identifiers: flag(opts, "bracket_identifiers", true),
                dialect: opts
                    .get("dialect")
                    .and_then(Value::as_str)
                    .map(String::from),
            };
            json!(is_readonly_sql(sql, &options))
        }
        Some("split_sql_statements") => json!(split_sql_statements(
            sql,
            flag(opts, "bracket_identifiers", true),
            flag(opts, "reject_executable_comments", false),
        )),
        Some("duckdb_writes_only_main") => json!(duckdb_writes_only_main(sql)),
        Some("duckdb_copy_export_target") => json!(duckdb_copy_export_target(sql)),
        _ => json!("unknown fn"),
    }
}

fn main() {
    let stdin = std::io::stdin();
    let stdout = std::io::stdout();
    let mut out = stdout.lock();
    for line in stdin.lock().lines() {
        let line = line.expect("stdin");
        if line.trim().is_empty() {
            continue;
        }
        let item: Value = serde_json::from_str(&line).expect("json line");
        writeln!(out, "{}", json!({ "rs": run(&item) })).expect("stdout");
    }
}
