#!/usr/bin/env python3
"""Compare Parable ASTs with the Rable-based adapter in dippy-rs.

Runs ``ast_dump.py`` (Parable) and ``dippy-rs --dump-ast-jsonl`` (Rable) over
every corpus command and reports where the Parable-shaped trees differ.
Writes rust/parity/ast-report.md.
"""

from __future__ import annotations

import collections
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
BIN = HERE.parent / "target" / "release" / "dippy-rs"


def first_diff(a, b, path="$"):
    if type(a) is not type(b):
        return path, a, b
    if isinstance(a, dict):
        for key in sorted(set(a) | set(b)):
            if key not in a or key not in b:
                return f"{path}.{key}", a.get(key, "<missing>"), b.get(key, "<missing>")
            found = first_diff(a[key], b[key], f"{path}.{key}")
            if found:
                return found
        return None
    if isinstance(a, list):
        if len(a) != len(b):
            return f"{path}[len]", len(a), len(b)
        for i, (x, y) in enumerate(zip(a, b)):
            found = first_diff(x, y, f"{path}[{i}]")
            if found:
                return found
        return None
    return None if a == b else (path, a, b)


def shape(path: str) -> str:
    import re

    return re.sub(r"\[\d+\]", "[]", path)


def main() -> None:
    corpus = HERE / "corpus.jsonl"
    data = corpus.read_bytes()
    py = subprocess.run(
        [str(REPO / ".venv-3.12" / "bin" / "python"), str(HERE / "ast_dump.py")],
        input=data, capture_output=True, check=True,
    ).stdout.decode().splitlines()
    rs = subprocess.run(
        [str(BIN), "--dump-ast-jsonl"], input=data, capture_output=True, check=True
    ).stdout.decode().splitlines()
    cases = [json.loads(line) for line in data.decode().splitlines() if line.strip()]
    assert len(py) == len(rs) == len(cases), (len(py), len(rs), len(cases))
    groups = collections.defaultdict(list)
    seen_cmds = set()
    total = 0
    for case, a, b in zip(cases, py, rs):
        if case["cmd"] in seen_cmds:
            continue
        seen_cmds.add(case["cmd"])
        total += 1
        pa, rb = json.loads(a), json.loads(b)
        diff = first_diff(pa, rb)
        if diff:
            path, x, y = diff
            groups[shape(path)].append((case["cmd"], x, y))
    ndiff = sum(len(v) for v in groups.values())
    lines = [
        "# Parser divergence report (Parable vs Rable adapter)",
        "",
        "Generated by `rust/parity/ast_compare.py`. Compares the Parable-shaped",
        "AST fields Dippy's analyzer reads. Not a decision comparison.",
        "",
        f"- Distinct commands: {total}",
        f"- Identical trees: {total - ndiff}",
        f"- Divergent trees: {ndiff}",
        "",
    ]
    for key, items in sorted(groups.items(), key=lambda kv: -len(kv[1])):
        lines.append(f"## `{key}` ({len(items)})")
        lines.append("")
        for cmd, x, y in items[:8]:
            short = lambda v: json.dumps(v)[:160]
            lines.append(f"- `{json.dumps(cmd)[1:-1][:140]}`: Parable `{short(x)}` / Rable `{short(y)}`")
        lines.append("")
    (HERE / "ast-report.md").write_text("\n".join(lines))
    print(f"{total} commands, {ndiff} divergent, {len(groups)} groups")
    for key, items in sorted(groups.items(), key=lambda kv: -len(kv[1]))[:25]:
        print(len(items), key, "|", json.dumps(items[0][0])[:80], "|", json.dumps(items[0][1])[:80], "|", json.dumps(items[0][2])[:80])


if __name__ == "__main__":
    sys.exit(main())
