//! Generate the built-in allowlists from the Python source so the two
//! implementations cannot drift (`src/dippy/core/allowlists.py`).

use std::path::PathBuf;

fn frozenset_strings(source: &str, name: &str) -> Vec<String> {
    let start = source
        .find(&format!("{name} = frozenset("))
        .unwrap_or_else(|| panic!("{name} not found in allowlists.py"));
    let body = &source[start..];
    let end = body.find("\n)").expect("unterminated frozenset");
    let mut out = Vec::new();
    for line in body[..end].lines() {
        let code = line.split('#').next().unwrap_or("");
        let mut rest = code;
        while let Some(open) = rest.find('"') {
            let after = &rest[open + 1..];
            let Some(close) = after.find('"') else { break };
            out.push(after[..close].to_string());
            rest = &after[close + 1..];
        }
    }
    out
}

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let py = manifest.join("../../src/dippy/core/allowlists.py");
    println!("cargo:rerun-if-changed={}", py.display());
    let source = std::fs::read_to_string(&py).expect("read allowlists.py");
    let mut code = String::from("// Generated by build.rs from src/dippy/core/allowlists.py.\n");
    for name in ["SIMPLE_SAFE", "WRAPPER_COMMANDS"] {
        let items = frozenset_strings(&source, name);
        assert!(!items.is_empty(), "{name} is empty");
        code.push_str(&format!("pub static {name}_LIST: &[&str] = &{items:?};\n"));
    }
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("allowlists.rs");
    std::fs::write(out, code).unwrap();
}
